## The purpose of this notebook is to aid in the process of writing tests

Joe Abbott

# 1. test_NNModels.py

In [ ]:
from NNModels import *

In [ ]:
smiles = 'C[C@@H](CC1=CC=CC=C1)NC'

In [ ]:
smiles2 = 'C1=CC=CC=C1'

In [ ]:
molecule = NNModels.Descriptors(smiles)

In [ ]:
mol_obj = NNModels.Descriptors(smiles1)
type(mol_obj)

In [ ]:
for val in mol_obj.get_properties().values():
#     assert isinstance(val, float)
    print(val)

In [ ]:
mol_obj.set_molecule(smiles2)
type(mol_obj)

In [ ]:
mol_obj.get_features()

In [ ]:
cm = molecule.get_coulomb_matrix()

In [ ]:
type(cm)

In [ ]:
test_fp = mol_obj.get_Morgan_fingerprint(nBits=2048, use_features=True)
test_fp
sum = 0
for i in test_fp: 
    sum += sum + i
print(str(sum))

In [ ]:
molecule.__get_charges_coords()

# 2. test_utilities.py

In [ ]:
from utilities import *
import rdkit

In [ ]:
smiles = 'C[C@@H](CC1=CC=CC=C1)NC'
filename = 'draw1'

In [ ]:
draw_molecule(smiles, filename)

In [ ]:
import rdkit.Chem.Draw as draw
mol = Chem.MolFromSmiles(smiles)
draw.MolToFile(mol, filename, kekulize=False)

In [ ]:
import time

def print_hello():
    
    start = time.time()
    print('hello')
    end = time.time()
    print('Elapsed time:' + str(end - start))
    
    return

In [ ]:
print_hello()

In [ ]:
a = None

In [ ]:
type(None)

In [ ]:
assert isinstance(a, (str, type(None)))

In [ ]:
import numpy as np

In [ ]:
filename = 'draw1.png'
assert filename.endswith('.png') or filename.endswith('.pdf')

In [ ]:
my_strings = [1223.0, 1234.0, 123]

In [ ]:
remove_deliminators(['1,000,000'])

In [ ]:
asdf = 'CCC'

if asdf != 'CCH':
    raise RuntimeError('function wrong')
#     print('hi')
else:
    print('what')

In [ ]:
asdf == 'CCH'

In [ ]:
if testSMILES == removed1:
        pass
    else:
        raise RuntimeError, "Error: function removing \
            counterions that don't exist!"

In [ ]:
test_dict = {0:[1, 2, 3], 1:[1, 2, 3, 4, 5]}

In [ ]:
len(test_dict)

In [ ]:
out = pad_ndarrays(test_dict)

In [ ]:
len(out)

In [ ]:
test_df = pd.DataFrame({'#':[0,1,2], 'SMILES':['C1=CC=CC=C1','CC1=CC=CC=C1','CC1=CC=CC=C1C']})
test_keyname = '#'

In [ ]:
compute_fingerprints(test_df, test_keyname)

In [ ]:
asdf = 'hsdkj'
assert isinstance(asdf, str)

In [ ]:
test_df = pd.DataFrame({'#':[0,1,2],\
    'SMILES':['C1=CC=CC=C1','CC1=CC=CC=C1','CC1=CC=CC=C1C']})
test_keyname = '#'

In [ ]:
test_df

In [ ]:
out_dict = compute_fingerprints(test_df, key_name=test_keyname)

In [ ]:
len(out_dict)

In [ ]:
len(test_df)

In [ ]:
out_cm = compute_coulumb_matrixes(test_df, key_name=test_keyname)
out_eig = compute_coulumb_matrixes(test_df, key_name=test_keyname, 
                                   use_eigval=True)

In [ ]:
len(out_eig.values())

In [ ]:
len(test_df)

In [ ]:
test_df = pd.DataFrame({'#':[0,1,2],\
    'SMILES':['C1=CC=CC=C1','CC1=CC=CC=C1','CC1=CC=CC=C1C']})
test_keyname = '#'
out_prop = compute_properties(test_df, index_name=test_keyname, output_file='test_feat.txt')
# len(out_prop)

In [ ]:
output_file = 'jsgkj.tx'
type(output_file)

In [ ]:
if type(output_file) == str:
    assert output_file.endswith('.txt'),'output_file string must include the .txt extension'

In [ ]:
import os
os.path.isfile('../setup.py')

In [ ]:
visualize(['CCC', 200, 1, 250, 1])

In [ ]:
coords = broaden_spectrum([200, 1], 5.0)

In [ ]:
y = max(coords[1])

In [ ]:
np.isclose(y, 1)

In [ ]:
wavelength_intensity = np.array([[400, 0.5], [500, 1]])

In [ ]:
wavelength_intensity.view('f8,f8').sort(order=['f1'], axis = 0)
lambda_max = wavelength_intensity[-1][0]

In [ ]:
lambda_max

In [ ]:
from utilities import draw_molecule
import NNModels
import numpy as np

In [ ]:
smiles = 'C1=CC=CC=C1'

In [ ]:
molecule = NNModels.Descriptors(smiles)

In [ ]:
filename = './frontend/draw_test.png'
draw_molecule(smiles, filename)

In [ ]:
x = np.array([5,5,5])
y = np.array([6,6,6])

In [ ]:
assert isinstance()

## 3. test_model_utils.py

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
xtrain_test = np.array([[1, 2, 3],[4,5,6]])
xtest_test  = np.array([[4, 5, 6], [7,8,9]])
ytrain_test = np.array([7, 8])
ytest_test  = np.array([10, 11])
filename = 'model_error_test_plot.png'
model = LinearRegression().fit(xtrain_test.reshape(1,-1), ytrain_test.reshape(1,-1))
label = 'Abs'

In [ ]:
assert isinstance(xtrain_test, np.ndarray)

In [3]:
nd_arrays = [np.array([1,2,3]), np.array([3,4,5])]

In [1]:
from model_utils import ModelUtils as Models
import numpy as np
cc = Models.combine_columns([np.array([1,2,3]), np.array([3,4,5])])
cc

array([[1, 3],
       [2, 4],
       [3, 5]])

In [5]:
len(cc)

3

In [7]:
l_prev = len(nd_arrays[0])
for i in range(1, len(nd_arrays)):
    l = len(nd_arrays[i])
    assert l == l_prev, \
        'Array at index ' + str(i) + ' is the wrong size. ' \
        'All arrays in input array must be the same length'
    l_prev = l

In [4]:
len(nd_arrays[0])

3

In [ ]:
l_prev = len(nd_arrays[0])
for i in range(1, len(nd_arrays)):
    l = len(nd_arrays[i])
    assert l == l_prev, \
        'Array at index ' + str(i) + ' is the wrong size. ' \
        'All arrays in input array must be the same length'
    l_prev = l
    
    

In [ ]:
nd_arrays.shape

In [ ]:
cc.shape

In [ ]:
from model_utils import ModelUtils as Models
import numpy as np

In [8]:
y_actual = np.array([1, 2, 3,3,3,3,3, 4, 5, 6, 7, 8, 9, 10])
disc = Models.get_y_category(y_actual, 1, 3)

In [9]:
disc

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3])

In [10]:
counts = Models.get_class_count(disc)

In [11]:
counts

{0: 7, 1: 3, 2: 3, 3: 1}

In [ ]:
len(counts)

In [17]:
dataset = Models.combine_columns([y_actual, disc])
dataset

array([[ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 3,  0],
       [ 3,  0],
       [ 3,  0],
       [ 3,  0],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  3]])

In [20]:
ss_data = Models.subsampling(dataset, 1, 3,counts)
len(ss_data[0])


2

In [21]:
len(dataset[0])

2