In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dataUtils import DataUtils as utils
from model_utils import ModelUtils as mutls

C:\Users\Yang\.conda\envs\test_speedcom\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
from keras import Sequential
from keras.layers import Dense, Embedding, LSTM, GRU, Conv1D, Activation

Using TensorFlow backend.


In [3]:
df=pd.read_csv('temp_cfprint.tsv', sep='\t')

In [4]:
df.head()

#      Name      name_smiles  Wavelength  Epsilon  Quantum Yield  \
0  1   Benzene      C1=CC=CC=C1      254.75      210          0.053   
1  2   Toluene     CC1=CC=CC=C1      261.75     2860          0.170   
2  3  o-Xylene    CC1=CC=CC=C1C      263.00      254          0.170   
3  4  m-Xylene  CC1=CC(=CC=C1)C      265.00      284          0.130   
4  5  p-Xylene  CC1=CC=C(C=C1)C      275.00      770          0.220   

                                                 cfp  
0  [224, 255, 255, 255, 0, 8, 0, 0, 3, 0, 0, 0, 2...  
1  [224, 255, 255, 255, 0, 8, 0, 0, 11, 0, 0, 0, ...  
2  [224, 255, 255, 255, 0, 8, 0, 0, 10, 0, 0, 0, ...  
3  [224, 255, 255, 255, 0, 8, 0, 0, 12, 0, 0, 0, ...  
4  [224, 255, 255, 255, 0, 8, 0, 0, 8, 0, 0, 0, 1...

In [5]:
X_fp=utils.finger_print_clean(df=df,colname_string_array='cfp')

fingerprint column shape is (267, 137)


In [6]:
X_fp.shape

(267, 137)

In [8]:
Y = df.values[:,3]

### First model original Y

In [9]:
d_cat = mutls.combine_columns((X_fp, Y))

In [11]:
X, y = d_cat[:,0:-1], d_cat[:,-1]

In [41]:
y

array([254.75, 261.75, 263.0, 265.0, 275.0, 265.0, 278.0, 271.0, 271.0,
       270.75, 220.0, 222.0, 242.0, 227.0, 241.0, 288.0, 251.0, 279.0,
       265.0, 228.0, 258.0, 248.0, 236.0, 274.0, 277.0, 227.0, 222.0,
       218.0, 310.25, 291.0, 240.0, 251.0, 263.0, 245.0, 302.0, 252.0,
       283.0, 225.0, 316.0, 230.0, 442.0, 247.5, 276.25, 294.75, 312.0,
       251.0, 206.0, 209.0, 212.0, 245.0, 223.0, 278.0, 275.0, 356.25,
       475.0, 578.0, 252.0, 241.0, 258.0, 372.5, 270.25, 303.0, 228.0,
       239.0, 245.0, 218.0, 227.0, 235.0, 278.75, 276.0, 293.75, 326.0,
       330.0, 353.25, 432.25, 425.0, 372.0, 451.0, 251.0, 276.0, 227.0,
       257.0, 265.0, 270.0, 215.0, 281.0, 238.0, 204.0, 219.0, 245.0,
       217.0, 253.0, 231.75, 206.0, 278.0, 502.0, 413.0, 286.0, 336.0,
       460.5, 219.0, 413.0, 247.0, 349.0, 262.0, 257.5, 274.25, 211.0,
       278.0, 261.0, 243.0, 266.75, 263.75, 258.25, 228.0, 259.0, 212.0,
       263.0, 265.0, 206.0, 248.0, 281.0, 239.75, 225.0, 288.0, 211.0,
  

In [15]:
X_train, X_test, y_train, y_test = utils.splitData(X, y, ratio=0.20)


In [31]:
unique_int_counts = len(np.unique(X_train))

In [45]:
np.unique(X_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 88, 89, 90,
       92, 93, 94, 95, 96, 97, 98, 100, 101, 102, 104, 105, 106, 108, 109,
       110, 112, 113, 114, 116, 117, 118, 120, 121, 122, 124, 125, 126,
       128, 129, 130, 132, 133, 134, 136, 137, 138, 140, 141, 142, 144,
       145, 146, 148, 149, 150, 152, 153, 154, 156, 157, 158, 160, 161,
       162, 164, 165, 166, 168, 169, 170, 172, 173, 174, 176, 177, 178,
       180, 181, 182, 184, 185, 186, 188, 189, 190, 192, 193, 194, 196,
       197, 198, 200, 201, 202, 204, 205, 206, 208, 209, 210, 212, 213,
       214, 216, 217, 218, 220, 221, 222, 224, 225, 226, 228, 229, 230,
       232, 233, 234, 236, 237, 238, 240, 241, 2

In [46]:
unique_int_counts

212

In [43]:
X_train.shape

(213, 137)

In [20]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding, Dropout, Flatten

In [51]:
hidden_size = 50
model = Sequential()
model.add(Embedding(X.shape[1], hidden_size, input_length= X.shape[1]))
model.add(LSTM(hidden_size, return_sequences=True))
model.add(LSTM(hidden_size, return_sequences=True))
model.add(LSTM(hidden_size, return_sequences=True))
model.add(Dropout(0.4))
model.add(Dense(hidden_size, activation='relu'))
model.add(Flatten())
model.add(Dense(1, activation='linear'))

In [52]:
model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['mean_absolute_error'])
model.summary() ##use mean_squared_error loss

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 137, 50)           6850      
_________________________________________________________________
lstm_16 (LSTM)               (None, 137, 50)           20200     
_________________________________________________________________
lstm_17 (LSTM)               (None, 137, 50)           20200     
_________________________________________________________________
lstm_18 (LSTM)               (None, 137, 50)           20200     
_________________________________________________________________
dropout_5 (Dropout)          (None, 137, 50)           0         
_________________________________________________________________
dense_9 (Dense)              (None, 137, 50)           2550      
_________________________________________________________________
flatten_5 (Flatten)          (None, 6850)              0         
__________

In [53]:
model.fit(X_train, y_train, batch_size=32, validation_data=(X_test, y_test), epochs=100)

Train on 213 samples, validate on 54 samples
Epoch 1/100


InvalidArgumentError: indices[30,0] = 224 is not in [0, 137)
	 [[{{node embedding_6/embedding_lookup}}]]

### Second model, category model

In [8]:
Y_category = mutls.get_y_category(y_actual=Y, min_edge=200, bin_width=20)

In [10]:
cls_counts = mutls.get_class_count(Y_category)

In [11]:

print(cls_counts)

{0.0: 18, 1.0: 23, 2.0: 40, 3.0: 44, 4.0: 14, 5.0: 7, 6.0: 8, 7.0: 4, 8.0: 6, 9.0: 3, 10.0: 12, 11.0: 10, 12.0: 7, 13.0: 4, 14.0: 7, 15.0: 10, 16.0: 5, 17.0: 10, 18.0: 6, 19.0: 6, 20.0: 6, 21.0: 3, 22.0: 4, 23.0: 2, 24.0: 2, 25.0: 2, 28.0: 1, 29.0: 2, 30.0: 1}


In [20]:
X_fp.shape

(267, 137)

In [22]:
d_cat = mutls.combine_columns((X_fp, Y_category))

In [23]:
subsampled=mutls.subsampling(d_cat,-1,15,cls_counts)

In [24]:
subsampled

array([[224, 255, 255, ..., 0, 0, 3.0],
       [224, 255, 255, ..., 0, 0, 3.0],
       [224, 255, 255, ..., 0, 0, 3.0],
       ...,
       [224, 255, 255, ..., 0, 0, 10.0],
       [224, 255, 255, ..., 0, 0, 10.0],
       [224, 255, 255, ..., 0, 0, 29.0]], dtype=object)

In [28]:
X, y = subsampled[:,0:-1], subsampled[:,-1]
y_onehot = mutls.onehot_encode_y(y=y, num_class=31)
X_train, X_test, y_train, y_test = utils.splitData(X, y_onehot, ratio=0.10)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(179, 137)
(20, 137)
(179, 31)
(20, 31)


### 2nd fingerprint model RNN LSTM with category Y

In [36]:
X_train = X_train.reshape((X_train.shape[0],X_train.shape[1],1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

rnn1_size = 224
rnn2_size = 384
dropout_rate = 0.2
loss = 'categorical_crossentropy'
metrics = ['accuracy']
num_classes = 31
optimizer = 'adam' #use adam optimizer

model_1 = Sequential()
model_1.add(LSTM(rnn1_size, return_sequences=True, input_shape=(137,1))) #137
model_1.add(LSTM(rnn2_size))
model_1.add(Dense(num_classes, activation='softmax'))
model_1.compile(optimizer=optimizer, loss=loss, metrics=metrics)
model_1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 137, 224)          202496    
_________________________________________________________________
lstm_4 (LSTM)                (None, 384)               935424    
_________________________________________________________________
dense_2 (Dense)              (None, 31)                11935     
Total params: 1,149,855
Trainable params: 1,149,855
Non-trainable params: 0
_________________________________________________________________


In [37]:
batch_size = 16
epochs = 100

model_1.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=[X_test, y_test])

Instructions for updating:
Use tf.cast instead.
Train on 179 samples, validate on 20 samples
Epoch 1/100
179/179 [==============================] - 10s 57ms/step - loss: 3.4145 - acc: 0.0894 - val_loss: 3.2352 - val_acc: 0.0500
Epoch 2/100
179/179 [==============================] - 8s 46ms/step - loss: 3.2857 - acc: 0.0838 - val_loss: 3.1650 - val_acc: 0.1000
Epoch 3/100
179/179 [==============================] - 8s 46ms/step - loss: 3.1737 - acc: 0.0838 - val_loss: 3.0942 - val_acc: 0.0500
Epoch 4/100
179/179 [==============================] - 8s 46ms/step - loss: 3.1800 - acc: 0.0894 - val_loss: 3.0205 - val_acc: 0.0500
Epoch 5/100
179/179 [==============================] - 8s 47ms/step - loss: 3.1538 - acc: 0.1061 - val_loss: 3.3127 - val_acc: 0.1000
Epoch 6/100
179/179 [==============================] - 9s 48ms/step - loss: 3.2281 - acc: 0.0838 - val_loss: 3.2009 - val_acc: 0.1000
Epoch 7/100
179/179 [==============================] - 9s 49ms/step - loss: 3.0486 - acc: 0.1117 - val

179/179 [==============================] - 9s 48ms/step - loss: 2.2766 - acc: 0.2179 - val_loss: 3.2231 - val_acc: 0.0500
Epoch 60/100
179/179 [==============================] - 9s 48ms/step - loss: 2.3147 - acc: 0.2235 - val_loss: 3.2866 - val_acc: 0.0000e+00
Epoch 61/100
179/179 [==============================] - 9s 48ms/step - loss: 2.2778 - acc: 0.2458 - val_loss: 3.7908 - val_acc: 0.1000
Epoch 62/100
179/179 [==============================] - 9s 48ms/step - loss: 2.5234 - acc: 0.2011 - val_loss: 3.3509 - val_acc: 0.1000
Epoch 63/100
179/179 [==============================] - 9s 48ms/step - loss: 2.4305 - acc: 0.2011 - val_loss: 3.5701 - val_acc: 0.0500
Epoch 64/100
179/179 [==============================] - 9s 48ms/step - loss: 2.3638 - acc: 0.1844 - val_loss: 3.2587 - val_acc: 0.0000e+00
Epoch 65/100
179/179 [==============================] - 9s 50ms/step - loss: 2.3181 - acc: 0.2123 - val_loss: 3.2376 - val_acc: 0.0000e+00
Epoch 66/100
179/179 [==============================] - 

Training acc 0.25, testing accuracy 0.05 (max 0.15)