In [24]:
import pandas as pd
import numpy as np
from utilities import compute_coulumb_matrixes

In [25]:
data=pd.read_csv('cleaned_data_emission.tsv',sep='\t')

In [26]:
c_mtx = compute_coulumb_matrixes(data, SMILES_column='SMILES')

KeyboardInterrupt: 

In [27]:
c_mtx_eig = compute_coulumb_matrixes(data, use_eigval=True, SMILES_column='SMILES')

In [3]:
from NNModels import Descriptors

In [4]:
spD = Descriptors(data.SMILES[0])

In [5]:
a = spD.get_coulomb_matrix(output_eigval=True)

In [13]:
a.sort()

In [26]:
data.SMILES[0]

'C1=CC=CC=C1'

In [14]:
np.argsort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a.dtype

dtype('float64')

In [15]:
a

array([-1.17120788e+00, -5.92546555e-01, -5.92546481e-01, -2.41567563e-01,
       -2.41567522e-01, -1.93810422e-02,  3.26545532e+00,  9.71045055e+00,
        9.71045170e+00,  3.55721137e+01,  3.55721215e+01,  1.33176856e+02])

In [5]:
len(c_mtx)

291

In [7]:
a = np.array(c_mtx[0])

In [8]:
a.shape

(181, 181)

In [16]:
from sklearn.decomposition import PCA

In [43]:
spD.set_molecule(data.SMILES[168])

In [44]:
a = spD.get_coulomb_matrix()

In [45]:
a.shape

(37, 37)

In [49]:
pca = PCA(n_components=37)

In [50]:
pca.fit(a)

PCA(copy=True, iterated_power='auto', n_components=37, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [54]:
pca.explained_variance_ratio_

array([4.42206862e-01, 1.68702718e-01, 1.48315051e-01, 7.25698707e-02,
       4.51724551e-02, 3.11127868e-02, 2.06426017e-02, 1.68015500e-02,
       1.61933814e-02, 1.37041068e-02, 7.73088226e-03, 7.51186626e-03,
       3.10700432e-03, 1.51799685e-03, 1.37237784e-03, 1.27787063e-03,
       7.85282160e-04, 5.96394581e-04, 3.71108425e-04, 1.17812831e-04,
       8.71207156e-05, 2.68349366e-05, 1.89693356e-05, 1.70483973e-05,
       7.83732911e-06, 7.00968783e-06, 5.58694700e-06, 4.91095846e-06,
       3.92544410e-06, 3.82997025e-06, 3.52752225e-06, 1.26734149e-06,
       9.27749960e-07, 9.10948675e-07, 1.64297676e-07, 1.49134745e-07,
       8.25392038e-32])

In [52]:
print(pca.singular_values_) 

[1.65991538e+02 1.02526056e+02 9.61315229e+01 6.72436664e+01
 5.30530135e+01 4.40293898e+01 3.58637276e+01 3.23554828e+01
 3.17644969e+01 2.92212357e+01 2.19476355e+01 2.16345135e+01
 1.39137482e+01 9.72542625e+00 9.24719589e+00 8.92311837e+00
 6.99497354e+00 6.09593116e+00 4.80865497e+00 2.70937742e+00
 2.32988200e+00 1.29307435e+00 1.08717453e+00 1.03065897e+00
 6.98807009e-01 6.60879908e-01 5.90011512e-01 5.53167097e-01
 4.94558430e-01 4.88507134e-01 4.68822116e-01 2.81008875e-01
 2.40430014e-01 2.38243008e-01 1.01178659e-01 9.63968023e-02
 7.17139010e-14]


In [38]:
data.SMILES[168]

'C1=CC=C(C=C1)[N+]2=C3C=C(C=CC3=NC4=C2C=C(C=C4)N)N'